### ISSUE TITLE
Error: There are no valid OpenCL platforms in the system

### ISSUE THREAD

**Issue by Andrew-H2O** [buddhi1980/mandelbulber2#592]
##### System information (version)

- mandelbulber2 => 2.15
- Operating System / Platform => Windows 10 64 Bit
- Compiler => ??  (Downloaded precompiled installer)

##### Detailed description

Downloaded and installed Mandelbulber 2.15, having previously successfully used 2.15-alpha 3 and previous.  When launching, I get error message "Error: There are no valid OpenCL platforms in the system"
The application starts, but without OpenCL support.

Last lines of the mandelbulber_log.txt file are as follows;

PID: 9980, time: 0.074, cSettings::Decode(cParameterContainer *par, cFractalContainer *fractPar, cAnimationFrames *frames)
PID: 9980, time: 0.085, Critical: OpenCl ERROR:  "cl::Platform::get"  ( -1 ) (c:\projects\mandelbulber2\mandelbulber2\src\opencl_hardware.cpp:300, bool __cdecl cOpenClHardware::checkErr(int,class QString)
PID: 9980, time: 0.085, Error: There are no valid OpenCl platforms in the system

##### Steps to reproduce

As above

**Comment by buddhi1980** [comment]
What GFX card do you use? Which version of gfx driver do you use?
Have tiy tried to update od downgrade gfx drive? I'm asking, because it sound like problem with gfx driver in the system which is responsible to provide OpenCL platform.
If you run  2.15-alpha 3 do you get the same message?

**Comment by Andrew-H2O** [comment]
Sorry - some additional details:  I have a GTX 1080Ti, running drivers version 416.81
Currently updating to 416.94 to see if it makes a difference.

2.15-aplha 3 ran without this problem, as did previous alphas and release versions.

**Comment by buddhi1980** [comment]
I'm asking of now 2.15-aplha 3 runs properly. Can you test it?

**Comment by Andrew-H2O** [comment]
Upgrade to Nvidia drivers version 416.94 and restart hasn't helped.

**Comment by buddhi1980** [comment]
Try to one of examples from this site to check if OpenCl works: http://developer.download.nvidia.com/compute/cuda/3_0/sdk/website/OpenCL/website/samples.html

**Comment by Andrew-H2O** [comment]
I visited that page, but every Windows download (x86 or 64 bit) gives a 404-not found error.

**Comment by buddhi1980** [comment]
Try from here: https://developer.nvidia.com/opencl

**Comment by Andrew-H2O** [comment]
New page is here: https://developer.nvidia.com/opencl

Downloaded OpenCL Marching Cubes Isosurfaces, and it runs without problem.

**Comment by buddhi1980** [comment]
Can you run OpenCL Device Query and paste output here?

**Comment by Andrew-H2O** [comment]
Output of OpenCL Device Query:

C:\Users\........\Downloads\oclDeviceQuery\NVIDIA GPU Computing SDK\OpenCL\bin\win64\Release\oclDeviceQuery.exe Starting...

OpenCL SW Info:

 CL_PLATFORM_NAME: 	NVIDIA CUDA
 CL_PLATFORM_VERSION: 	OpenCL 1.2 CUDA 10.0.132
 OpenCL SDK Revision: 	7027912


OpenCL Device Info:

 1 devices found supporting OpenCL:

 ---------------------------------
 Device GeForce GTX 1080 Ti
 ---------------------------------
  CL_DEVICE_NAME: 			GeForce GTX 1080 Ti
  CL_DEVICE_VENDOR: 			NVIDIA Corporation
  CL_DRIVER_VERSION: 			416.94
  CL_DEVICE_VERSION: 			OpenCL 1.2 CUDA
  CL_DEVICE_OPENCL_C_VERSION: 		OpenCL C 1.2 
  CL_DEVICE_TYPE:			CL_DEVICE_TYPE_GPU
  CL_DEVICE_MAX_COMPUTE_UNITS:		28
  CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS:	3
  CL_DEVICE_MAX_WORK_ITEM_SIZES:	1024 / 1024 / 64 
  CL_DEVICE_MAX_WORK_GROUP_SIZE:	1024
  CL_DEVICE_MAX_CLOCK_FREQUENCY:	1721 MHz
  CL_DEVICE_ADDRESS_BITS:		64
  CL_DEVICE_MAX_MEM_ALLOC_SIZE:		2816 MByte
  CL_DEVICE_GLOBAL_MEM_SIZE:		11264 MByte
  CL_DEVICE_ERROR_CORRECTION_SUPPORT:	no
  CL_DEVICE_LOCAL_MEM_TYPE:		local
  CL_DEVICE_LOCAL_MEM_SIZE:		48 KByte
  CL_DEVICE_MAX_CONSTANT_BUFFER_SIZE:	64 KByte
  CL_DEVICE_QUEUE_PROPERTIES:		CL_QUEUE_OUT_OF_ORDER_EXEC_MODE_ENABLE
  CL_DEVICE_QUEUE_PROPERTIES:		CL_QUEUE_PROFILING_ENABLE
  CL_DEVICE_IMAGE_SUPPORT:		1
  CL_DEVICE_MAX_READ_IMAGE_ARGS:	256
  CL_DEVICE_MAX_WRITE_IMAGE_ARGS:	16
  CL_DEVICE_SINGLE_FP_CONFIG:		denorms INF-quietNaNs round-to-nearest round-to-zero round-to-inf fma 

  CL_DEVICE_IMAGE <dim>			2D_MAX_WIDTH	 16384
					2D_MAX_HEIGHT	 32768
					3D_MAX_WIDTH	 16384
					3D_MAX_HEIGHT	 16384
					3D_MAX_DEPTH	 16384

  CL_DEVICE_EXTENSIONS:			cl_khr_global_int32_base_atomics
					cl_khr_global_int32_extended_atomics
					cl_khr_local_int32_base_atomics
					cl_khr_local_int32_extended_atomics
					cl_khr_fp64
					cl_khr_byte_addressable_store
					cl_khr_icd
					cl_khr_gl_sharing
					cl_nv_compiler_options
					cl_nv_device_attribute_query
					cl_nv_pragma_unroll
					cl_nv_d3d10_sharing
					cl_khr_d3d10_sharing
					cl_nv_d3d11_sharing
					cl_nv_copy_opts


  CL_DEVICE_COMPUTE_CAPABILITY_NV:	6.1
  NUMBER OF MULTIPROCESSORS:		28
  NUMBER OF CUDA CORES:			4294967268
  CL_DEVICE_REGISTERS_PER_BLOCK_NV:	65536
  CL_DEVICE_WARP_SIZE_NV:		32
  CL_DEVICE_GPU_OVERLAP_NV:		CL_TRUE
  CL_DEVICE_KERNEL_EXEC_TIMEOUT_NV:	CL_TRUE
  CL_DEVICE_INTEGRATED_MEMORY_NV:	CL_FALSE
  CL_DEVICE_PREFERRED_VECTOR_WIDTH_<t>	CHAR 1, SHORT 1, INT 1, LONG 1, FLOAT 1, DOUBLE 1


  ---------------------------------
  2D Image Formats Supported (75)
  ---------------------------------
  #     Channel Order   Channel Type          

  1     CL_R            CL_FLOAT              
  2     CL_R            CL_HALF_FLOAT         
  3     CL_R            CL_UNORM_INT8         
  4     CL_R            CL_UNORM_INT16        
  5     CL_R            CL_SNORM_INT16        
  6     CL_R            CL_SIGNED_INT8        
  7     CL_R            CL_SIGNED_INT16       
  8     CL_R            CL_SIGNED_INT32       
  9     CL_R            CL_UNSIGNED_INT8      
  10    CL_R            CL_UNSIGNED_INT16     
  11    CL_R            CL_UNSIGNED_INT32     
  12    CL_A            CL_FLOAT              
  13    CL_A            CL_HALF_FLOAT         
  14    CL_A            CL_UNORM_INT8         
  15    CL_A            CL_UNORM_INT16        
  16    CL_A            CL_SNORM_INT16        
  17    CL_A            CL_SIGNED_INT8        
  18    CL_A            CL_SIGNED_INT16       
  19    CL_A            CL_SIGNED_INT32       
  20    CL_A            CL_UNSIGNED_INT8      
  21    CL_A            CL_UNSIGNED_INT16     
  22    CL_A            CL_UNSIGNED_INT32     
  23    CL_RG           CL_FLOAT              
  24    CL_RG           CL_HALF_FLOAT         
  25    CL_RG           CL_UNORM_INT8         
  26    CL_RG           CL_UNORM_INT16        
  27    CL_RG           CL_SNORM_INT16        
  28    CL_RG           CL_SIGNED_INT8        
  29    CL_RG           CL_SIGNED_INT16       
  30    CL_RG           CL_SIGNED_INT32       
  31    CL_RG           CL_UNSIGNED_INT8      
  32    CL_RG           CL_UNSIGNED_INT16     
  33    CL_RG           CL_UNSIGNED_INT32     
  34    CL_RA           CL_FLOAT              
  35    CL_RA           CL_HALF_FLOAT         
  36    CL_RA           CL_UNORM_INT8         
  37    CL_RA           CL_UNORM_INT16        
  38    CL_RA           CL_SNORM_INT16        
  39    CL_RA           CL_SIGNED_INT8        
  40    CL_RA           CL_SIGNED_INT16       
  41    CL_RA           CL_SIGNED_INT32       
  42    CL_RA           CL_UNSIGNED_INT8      
  43    CL_RA           CL_UNSIGNED_INT16     
  44    CL_RA           CL_UNSIGNED_INT32     
  45    CL_RGBA         CL_FLOAT              
  46    CL_RGBA         CL_HALF_FLOAT         
  47    CL_RGBA         CL_UNORM_INT8         
  48    CL_RGBA         CL_UNORM_INT16        
  49    CL_RGBA         CL_SNORM_INT16        
  50    CL_RGBA         CL_SIGNED_INT8        
  51    CL_RGBA         CL_SIGNED_INT16       
  52    CL_RGBA         CL_SIGNED_INT32       
  53    CL_RGBA         CL_UNSIGNED_INT8      
  54    CL_RGBA         CL_UNSIGNED_INT16     
  55    CL_RGBA         CL_UNSIGNED_INT32     
  56    CL_BGRA         CL_UNORM_INT8         
  57    CL_BGRA         CL_SIGNED_INT8        
  58    CL_BGRA         CL_UNSIGNED_INT8      
  59    CL_ARGB         CL_UNORM_INT8         
  60    CL_ARGB         CL_SIGNED_INT8        
  61    CL_ARGB         CL_UNSIGNED_INT8      
  62    CL_INTENSITY    CL_FLOAT              
  63    CL_INTENSITY    CL_HALF_FLOAT         
  64    CL_INTENSITY    CL_UNORM_INT8         
  65    CL_INTENSITY    CL_UNORM_INT16        
  66    CL_INTENSITY    CL_SNORM_INT16        
  67    CL_LUMINANCE    CL_FLOAT              
  68    CL_LUMINANCE    CL_HALF_FLOAT         
  69    CL_LUMINANCE    CL_UNORM_INT8         
  70    CL_LUMINANCE    CL_UNORM_INT16        
  71    CL_LUMINANCE    CL_SNORM_INT16        
  72    CL_BGRA         CL_SNORM_INT8         
  73    CL_BGRA         CL_SNORM_INT16        
  74    CL_ARGB         CL_SNORM_INT8         
  75    CL_ARGB         CL_SNORM_INT16        

  ---------------------------------
  3D Image Formats Supported (75)
  ---------------------------------
  #     Channel Order   Channel Type          

  1     CL_R            CL_FLOAT              
  2     CL_R            CL_HALF_FLOAT         
  3     CL_R            CL_UNORM_INT8         
  4     CL_R            CL_UNORM_INT16        
  5     CL_R            CL_SNORM_INT16        
  6     CL_R            CL_SIGNED_INT8        
  7     CL_R            CL_SIGNED_INT16       
  8     CL_R            CL_SIGNED_INT32       
  9     CL_R            CL_UNSIGNED_INT8      
  10    CL_R            CL_UNSIGNED_INT16     
  11    CL_R            CL_UNSIGNED_INT32     
  12    CL_A            CL_FLOAT              
  13    CL_A            CL_HALF_FLOAT         
  14    CL_A            CL_UNORM_INT8         
  15    CL_A            CL_UNORM_INT16        
  16    CL_A            CL_SNORM_INT16        
  17    CL_A            CL_SIGNED_INT8        
  18    CL_A            CL_SIGNED_INT16       
  19    CL_A            CL_SIGNED_INT32       
  20    CL_A            CL_UNSIGNED_INT8      
  21    CL_A            CL_UNSIGNED_INT16     
  22    CL_A            CL_UNSIGNED_INT32     
  23    CL_RG           CL_FLOAT              
  24    CL_RG           CL_HALF_FLOAT         
  25    CL_RG           CL_UNORM_INT8         
  26    CL_RG           CL_UNORM_INT16        
  27    CL_RG           CL_SNORM_INT16        
  28    CL_RG           CL_SIGNED_INT8        
  29    CL_RG           CL_SIGNED_INT16       
  30    CL_RG           CL_SIGNED_INT32       
  31    CL_RG           CL_UNSIGNED_INT8      
  32    CL_RG           CL_UNSIGNED_INT16     
  33    CL_RG           CL_UNSIGNED_INT32     
  34    CL_RA           CL_FLOAT              
  35    CL_RA           CL_HALF_FLOAT         
  36    CL_RA           CL_UNORM_INT8         
  37    CL_RA           CL_UNORM_INT16        
  38    CL_RA           CL_SNORM_INT16        
  39    CL_RA           CL_SIGNED_INT8        
  40    CL_RA           CL_SIGNED_INT16       
  41    CL_RA           CL_SIGNED_INT32       
  42    CL_RA           CL_UNSIGNED_INT8      
  43    CL_RA           CL_UNSIGNED_INT16     
  44    CL_RA           CL_UNSIGNED_INT32     
  45    CL_RGBA         CL_FLOAT              
  46    CL_RGBA         CL_HALF_FLOAT         
  47    CL_RGBA         CL_UNORM_INT8         
  48    CL_RGBA         CL_UNORM_INT16        
  49    CL_RGBA         CL_SNORM_INT16        
  50    CL_RGBA         CL_SIGNED_INT8        
  51    CL_RGBA         CL_SIGNED_INT16       
  52    CL_RGBA         CL_SIGNED_INT32       
  53    CL_RGBA         CL_UNSIGNED_INT8      
  54    CL_RGBA         CL_UNSIGNED_INT16     
  55    CL_RGBA         CL_UNSIGNED_INT32     
  56    CL_BGRA         CL_UNORM_INT8         
  57    CL_BGRA         CL_SIGNED_INT8        
  58    CL_BGRA         CL_UNSIGNED_INT8      
  59    CL_ARGB         CL_UNORM_INT8         
  60    CL_ARGB         CL_SIGNED_INT8        
  61    CL_ARGB         CL_UNSIGNED_INT8      
  62    CL_INTENSITY    CL_FLOAT              
  63    CL_INTENSITY    CL_HALF_FLOAT         
  64    CL_INTENSITY    CL_UNORM_INT8         
  65    CL_INTENSITY    CL_UNORM_INT16        
  66    CL_INTENSITY    CL_SNORM_INT16        
  67    CL_LUMINANCE    CL_FLOAT              
  68    CL_LUMINANCE    CL_HALF_FLOAT         
  69    CL_LUMINANCE    CL_UNORM_INT8         
  70    CL_LUMINANCE    CL_UNORM_INT16        
  71    CL_LUMINANCE    CL_SNORM_INT16        
  72    CL_BGRA         CL_SNORM_INT8         
  73    CL_BGRA         CL_SNORM_INT16        
  74    CL_ARGB         CL_SNORM_INT8         
  75    CL_ARGB         CL_SNORM_INT16        

oclDeviceQuery, Platform Name = NVIDIA CUDA, Platform Version = OpenCL 1.2 CUDA 10.0.132, SDK Revision = 7027912, NumDevs = 1, Device = GeForce GTX 1080 Ti

System Info: 

 Local Time/Date = 20:37:55, 11/19/2018
 CPU Arch: 9
 CPU Level: 6
 # of CPU processors: 8
 Windows Build: 9200
 Windows Ver: 6.2 (Windows Vista / Windows 7)

**Comment by buddhi1980** [comment]
Try to delete OpenCL.dll from the folder from where the program is launched and see what happen

**Comment by Andrew-H2O** [comment]
That appears to have fixed it!

Verified both with the alpha 3 and also 2.15 releases. (deleted from each respective folder before launching)

**Comment by buddhi1980** [comment]
Thanks a lot. It looks like OpenCL.dll shouldn't be attached to the program.

**Comment by mancoast** [comment]
Remove the ICD loader?

**Comment by buddhi1980** [comment]
I have just tested and got the same problem. But as I remember with older version of the driver it had to be in the program folder. This is something which I need to check.

**Comment by buddhi1980** [comment]
By the way this new NVidia driver has one more problem. Rendering is slower because workgroup size is always only 256.

**Comment by buddhi1980** [comment]
Final decision: we have to remove OpenCL.dll from the package. I have tested it with NVidia Driver 388 and also works without this DLL. 

About speed it is very strange. New driver (419) works faster with workgroup size 256 than old with workgroup size 512. Probably they optimized something in the compiler.

**Comment by buddhi1980** [comment]
I have just removed OpenCL.dll from the package. I hope I did it in correct way in commit (brach 2.15-bugfixes) https://github.com/buddhi1980/mandelbulber2/commit/203d5d9bf05380afcad8ba7fbf4df79dbbd4b3b3

**Comment by mancoast** [comment]
I think that’s right, hopefully appveyor packages everything correctly.

**Comment by buddhi1980** [comment]
Can any of you test if the newest Appveyor build (branch 2.15-bugfixes) runs on machines with clean system without OpenCL.dll?

**Comment by mclarekin** [comment]
i can try tomorrow if no one else has,

i would need steps for a  "machine with clean system without OpenCL.dll"

**Comment by buddhi1980** [comment]
Install the program on the system without NVidia or AMD driver, run the program and then try to render image without OpenCL. Open preferences and go to OpenCL tab. Try to enable OpenCL and see if OpenCL platforms are listed.

**Comment by buddhi1980** [comment]
Thanks for testing it.
@mancoast, we cannot require to have GPU to start the program. A lot of users uses just CPU for rendering and there is a lot of computing farms based on CPUs which doesn't have GPUs.

Now I know that OpenCL.dll is necessary to start the program. Without OpenCL ICD it reports that dll is missing and program cannot start.
Potential solutions:
- to attach newer version of OpenCL.dll and check if will work with NVidia driver in version 419 (@mancoast from where you get this OpenCL.dll file?)
- to have in package two exe files (like I did for old Mandelbulber v1): 
a) Mandelbulber-opencl.exe which requires OpenCL ICD and uses full capability of the program
b) Mandelbulber.exe which runs without OpenCL ICD and can render only using CPU
The program is already prepared to compile without OpenCL (when USE_OPENCL is not defined)
Both exe files could be compiled during one single run on appveyor (compiler would need to be run twice)
- like above but distribute two separate packages: one with OpenCL support and one without
- to use CLEW (dynamic loading of DLL) - it is not so good solution because CLEW is no longer developed and made a lot of troubles with include files for opencl headers
- to check during installation if OpenCL.dll is in the system and if not then copy to program folder. I think this solution will be complicated to implement.

There best for me would be first solution (if will work). If not work I would consider second and then third option. 

@mancoast , what you think?

**Comment by mancoast** [comment]
The attached opencl.dll was compiled from the Kronos source. First I need to try to replicate this issue on my systems. Then I will get back to you on this issue.

**Comment by buddhi1980** [comment]
Does your compilation of OpenCL IDE include this: https://github.com/KhronosGroup/OpenCL-ICD-Loader/commit/188be6047481ea3c0c2ba5a7583ee13c8c3b2333 ?
It looks like there was some important change in registration of ICDs. It was October 2017.

**Comment by Toys0125** [comment]
I fixed the issue by using DDU or display driver uninstaller and installing using the cuda installer.

**Comment by JanWerder** [comment]
I still have the issue with the Nvidia 417.01 driver. Removeing the Opencl.dll from the fodler didn't solve the issue.

**Comment by mancoast** [comment]
I will start a dialog on nvidia dev forums. Thanks for reporting!

**Comment by mancoast** [comment]
417.01 == BSOD on installation, 5 attempts to install on two separate systems (10 total). (x99 w/ 1050ti) (z97 w/ 780ti)
After multiple attempts, I cannot get the driver to install on my computers?
Something broken with NVIDIA?

**Comment by JanWerder** [comment]
I'm on the 417.01 driver with a NVIDIA GTX 1070/ Ryzen 1700. Just reinstalled to try it, but it works for me.

**Comment by mancoast** [comment]
@JanWerder I perfomred clean installation of Windows and  417.01 driver with a NVIDIA GTX 1050Ti.  The 2.15 release works without issues with the OpenCL.dll present in the mandelbulber2 application directory. @buddhi1980 Can you please retest this issue with the lastest NVidia driver and confirm that it still occurs. (I still cannot replicate the issue)

**Comment by buddhi1980** [comment]
@mancoast I will try it tomorrow once again

**Comment by JanWerder** [comment]
I can confirm that 2.15 doesnt work for me with the OpenCl.dll and the 417.01 driver present. I can try to replicate it tomorrow with VM.
    	
    	

    	
    
  




On Sat, Dec 1, 2018 at 9:36 PM +0100, "mancoast" <notifications@github.com> wrote:












@JanWerder I perfomred clean installation of Windows and  417.01 driver with a NVIDIA GTX 1050Ti.  The 2.15 release works without issues with the OpenCL.dll present in the mandelbulber2 application directory. @buddhi1980 Can you please retest this issue with the lastest NVidia driver and confirm that it still occurs. (I still cannot replicate the issue)

**Comment by mancoast** [comment]
Thanks! Also it might work for me because I’m running windows server, not windows 10. Maybe need w10 to replicate?

**Comment by mancoast** [comment]
I am able to replicate with clean installation of Windows 10 (not server) and Nvidia 417.01 driver with a NVIDIA GTX 1050Ti.  I have resolved the issue with recompilation of the ICD loader from opencl-icd-1.2.11.0-bin to opencl-icd-2.2.1.0-bin, however this only fixes x64, and x86 remains broken? @buddhi1980 have we officially dropped 32 bit support>?

**Comment by mclarekin** [comment]
a) good that it is fixed
b) "have we officially dropped 32 bit support" i think YES
c) I suggest, run populateOpenCL.php,(for me)  then ask on facebook for
some testing of latest dev version or we could release V2.15-1

**Comment by buddhi1980** [comment]
Thanks @mancoast for solving this problem. We already dropped win32 support.

**Comment by JanWerder** [comment]
Is there an AppVeyor Build for it? Or isn‘t the fix in master yet?
    	
    	

    	
    
  




On Sun, Dec 2, 2018 at 7:57 AM +0100, "Krzysztof Marczak" <notifications@github.com> wrote:












Thanks @mancoast for solving this problem. We already dropped win32 support.

**Comment by buddhi1980** [comment]
There is an AppVeyor build: https://ci.appveyor.com/project/buddhi1980/mandelbulber2/builds/20706384/job/3ibqeujuiofctttj/artifacts

**Comment by buddhi1980** [comment]
I have just tested and now works properly with 417.01
2.16 will have only a few improvements so this patch will be released very soon.
I need to clean up the code for selection of GPU devices, because it still doesn't work enough good (not possible to change GPU device without restart of the program).

**Comment by buddhi1980** [comment]
I think it can be closed. OpenC ICD problem is solved.
