### ISSUE TITLE
bug. Jos-Leys-Kleinian crashes MDBB2

### ISSUE THREAD

**Issue by TasMania17** [buddhi1980/mandelbulber2#599]
- mandelbulber2 => 2.16-dev
- Operating System / Platform => Ubuntu
- Compiler => qmake

Freshly compiled from source. OCL is now rendering very fast. Congratulations. The fract 'JosLeys-Kleinian' in any slot crashes my system.
No drama but this fract is a problem for me.

**Comment by mclarekin** [comment]
ok i think something is wrong, i will check it out

**Comment by mclarekin** [comment]
working ok for me, send some settings

**Comment by mclarekin** [comment]
i am testing in win10, i will check ubuntu later

**Comment by mclarekin** [comment]
but tell me
1) is this the first thing you have tried since download V2.16 dev
2) have you a lot of preset thumbnails on preset tool bar

**Comment by buddhi1980** [comment]
What you mean by "crashes my system"?

**Comment by TasMania17** [comment]
What you mean by "crashes my system"? Sorry, only MDBB crashes, system is OK.
1) is this the first thing you have tried since download V2.16 dev  - No so far other fracts working.
2) have you a lot of preset thumbnails on preset tool bar - No standard tool bar.
Could be how OCL interacts with this fract.

**Comment by mclarekin** [comment]
Crash to desk top,? or becomes unresponsive?

**Comment by TasMania17** [comment]
Crash to desktop. Tested with OCL 'off' and JosLeys renders OK.
With OCL 'on' it finishes 'Compiling OpenCL' programs then MBDD closes.

last lines of mandelbulber_log.txt:

PID: 4231, time: 0.061280351, cSettings::Decode(cParameterContainer *par, cFractalContainer *fractPar, cAnimationFrames *frames)
PID: 4231, time: 0.161167808, Critical: No OpenCL devices selected or selection or selected unknown devices!
 Selected first available GPU device
 Check program preferences to select correct GPU device (../src/opencl_hardware.cpp:367, void cOpenClHardware::EnableDevicesByHashList(const QString&)
PID: 4231, time: 39.758067868, Critical: OpenCl ERROR:  "CommandQueue::enqueueReadBuffer() for output-buffer"  ( -5 ) (../src/opencl_engine.cpp:73, static bool cOpenClEngine::checkErr(cl_int, QString)

**Comment by buddhi1980** [comment]
What GPU do you use? I tried it with GTX 1060 on Debian (nvidia-driver) and RX 580 on Ubuntu (AMDGPU-PRO driver) and works well
Can you provide settings which causes the problem?

**Comment by TasMania17** [comment]
GPU is Quadro K600 with 1024Mb ram. Maybe I'm overloading it. When I use this material:
![screenshot_2018-12-08_08-53-00](https://user-images.githubusercontent.com/32868462/49674674-ea873c00-fac6-11e8-930d-e96f8caaab30.png)
Select 'hybrid' then another fractal in slot 2 it crashes every time.

**Comment by buddhi1980** [comment]
What is this material? Does it have any big texture?

**Comment by TasMania17** [comment]
Hi buddhi  The texture is 1024x681 pixels.
[Marble3Fract.zip](https://github.com/buddhi1980/mandelbulber2/files/2658920/Marble3Fract.zip)

A nice material for fractals :)

**Comment by mclarekin** [comment]
I cannot make it crash,  .
 can you run in debug mode and supply a backtrace after crash?

**Comment by TasMania17** [comment]
Thanks for the help buddhi and mclarekin. I fixed the crashes by renamed the hidden ".mandelbulber" folder so it made a new one.
I think I compiled with debug on but don't know how to start in debug mode.

**Comment by mclarekin** [comment]
i think debug mode is available if you get the program using 

"prepare ubuntu for development" instructions

https://github.com/buddhi1980/mandelbulber2

**Comment by mclarekin** [comment]
yes, but  that generally means that the program becoming unresponsive
(semi-infinite calculation = program appears to freeze)  ,  not crash to
desktop.

 Some of the new formulas in openCL are missing some definitions, (working
on that at the moment), and I have a problem with new transt surfbox folds
v2 (that will crash the program)

If it is crashing on pre-v2.16 formulas, send us actual settings of any
crash, (although it might be your system)

"I fixed the crashes by renamed the hidden ".mandelbulber" folder so it
made a new one",  that should not be necessary  and we have not heard of
anyone else with this problem, (albeit very few are both linux and dev
version testers.  Over 70% of users download Winx64.)

**Comment by TasMania17** [comment]
Hi mclarekin, deleting that folder just let me render the Josleys fractal. I still get crashes to desktop using 'Full OpenCl mode'. I've found using fancy materials and increasing iterations makes it worse.

I realise this is a dev version so I'm using the default material and keeping iterations at 1. I can still play with OpenCL and do a final render in CPU mode.

This box is stable rendering other graphics apps (Kdenlive, Natron, Gimp)

IMHO Mandelbulber OCL still has some work to go but I've had glimpses of what it can do and it's very cool.

**Comment by buddhi1980** [comment]
@TasMania17, If you use Quadro K600, we can be surprised that it works at all. It is quite old technology which supports only OpenCL 1.1. Instability of the software become from lack of resources in GFX card, which cannot be handled by GFX driver.
Programs which you mentioned like Kdenlive, Natron, Gimp uses much simpler OpenCL or GLSL kernels which only filter images. In Mandelbulber there are huge rendering kernels. If you tell me that your card work stable with Blender in OpenCL mode, then we can start discussion.

**Comment by mclarekin** [comment]
Thanks for confirming Krzysztof .

Tas, to take advantage of the openCL features of  Mandelbulber you need a
better GFX card . (An early Xmas present to yourself).  Preferably at least
4GB card, and you will be amazed!!

**Comment by TasMania17** [comment]
Thanks for your advice guys. I will get one ASAP. The old card supports OCL 1.2 but Nvidia is up to OCL 4.6.
[https://en.wikipedia.org/wiki/List_of_Nvidia_graphics_processing_units](url)
I will close the issue.
